import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { getDb } from "./drizzle";
import { products } from "./schema";

// Scraped from https://www.tokopedia.com/abaholot
const tokpedProducts = [
  {
    id: "tokped-103520200915",
    name: "Jersey Lari Pria Drifit Milano Full Printing",
    type: "jersey",
    price: 98750,
    discountPrice: 125000,
    image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Best Seller",
    colors: ["Hitam", "Biru", "Merah"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Jersey lari pria dengan material Drifit Milano, full printing sublimasi. Cocok untuk lari, gym, futsal, sepeda. Bahan adem, cepat kering, dan nyaman dipakai.",
    materialJersey: "Drifit Milano",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Lari", "Gym", "Futsal", "Sepeda"],
  },
  {
    id: "tokped-103520152513",
    name: "Jersey Padel Tenis Benzema M-Tiis Anti UV",
    type: "jersey",
    price: 130000,
    discountPrice: 150000,
    image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Premium",
    colors: ["Hitam Gold"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Jersey olahraga padel tenis dengan teknologi M-Tiis anti UV. Sublimasi fullprint, quick dry, cocok untuk pria. Warna hitam gold yang elegan.",
    materialJersey: "M-Tiis Anti UV",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Padel", "Tenis", "Badminton"],
  },
  {
    id: "tokped-103423146226",
    name: "Jersey Wanita Padel Tenis Badminton Benzema",
    type: "jersey",
    price: 146500,
    discountPrice: 150000,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Multi"],
    description: "Jersey olahraga wanita anti UV dengan teknologi M-Tiis quickdry. Elastis, anti lembab, cocok untuk padel, tenis, badminton. Desain khusus ladies.",
    materialJersey: "M-Tiis Quickdry",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Padel", "Tenis", "Badminton", "Lari"],
  },
  {
    id: "tokped-103374273045",
    name: "Jersey Trail Motocross GRITRAIL Airflow",
    type: "jersey",
    price: 116500,
    discountPrice: 150000,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Adventure",
    colors: ["Hitam", "Hijau", "Merah"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Jersey trail motocross GRITRAIL dengan ventilasi airflow. Dry fit, cocok untuk cross, MTB, downhill. Desain agresif untuk adventure sejati.",
    materialJersey: "Dry Fit Airflow",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Trail", "Motocross", "MTB", "Downhill"],
  },
  {
    id: "tokped-102582457060",
    name: "CPX Set Cycling Jersey Gowes MTB + Celana",
    type: "set",
    price: 221500,
    discountPrice: 250000,
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Set",
    colors: ["Biru", "Merah", "Hitam"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "Set cycling jersey CPX Sport lengkap dengan celana. Baju gowes MTB lengan pendek + celana sepeda pria training panjang. Material premium, nyaman untuk gowes panjang.",
    materialJersey: "Dry Fit",
    materialCelana: "Spandek",
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Sepeda", "MTB", "Roadbike", "Gowes"],
  },
  {
    id: "tokped-102179275323",
    name: "Baju Jersey Sport Oversize CPX One Piece 07",
    type: "jersey",
    price: 109000,
    discountPrice: 150000,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Casual",
    colors: ["Hitam", "Putih", "Abu"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "Baju jersey sport oversize CPX One Piece. Desain casual santai, cocok untuk olahraga dan gaya sehari-hari. Join Nakama Sport!",
    materialJersey: "Cotton Combed 30s",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Casual", "Olahraga", "Hangout"],
  },
  {
    id: "tokped-103107304516",
    name: "CPX Vintage Jersey Ultras Indonesia",
    type: "jersey",
    price: 115000,
    discountPrice: 150000,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Vintage",
    colors: ["Biru", "Merah", "Hijau"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "CPX Vintage Jersey Ultras Indonesia. Baju dailywear retro fantasy, kaos dryfit untuk running, futsal, sport. Desain vintage yang unik.",
    materialJersey: "Dry Fit",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Futsal", "Running", "Casual", "Nobar"],
  },
  {
    id: "tokped-103107307432",
    name: "Jersey Olahraga Vintage Casual England Fantasy",
    type: "jersey",
    price: 95000,
    discountPrice: null,
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Vintage",
    colors: ["Biru Navy", "Merah Maroon"],
    sizes: ["S", "M", "L", "XL"],
    description: "Baju kaos jersey olahraga pria wanita model vintage casual England fantasy sport. Bahan nyaman, desain retro yang stylish.",
    materialJersey: "Cotton Combed 30s",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Casual", "Olahraga", "Futsal"],
  },
  {
    id: "tokped-cpx-polo-wangki",
    name: "CPX Set Jersey Kerah Wangki Polo + Celana Lari",
    type: "set",
    price: 175000,
    discountPrice: 200000,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Set",
    colors: ["Hitam", "Biru Navy", "Putih"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "CPX Sport set pakaian jersey kerah wangki kaos polo plus celana lari spandek pendek. Kombinasi elegan untuk olahraga dan casual.",
    materialJersey: "Dry Fit",
    materialCelana: "Spandek",
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Lari", "Golf", "Tenis", "Casual"],
  },
  {
    id: "tokped-cpx-running-set",
    name: "Set Running CPX Jersey Lari Elastis Adem + Celana",
    type: "set",
    price: 165000,
    discountPrice: 195000,
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Running",
    colors: ["Hitam", "Biru", "Abu"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "Set running CPX jersey olahraga lari elastis adem dengan celana olahraga spandek balon premium. Ringan, breathable, cocok untuk lari jarak jauh.",
    materialJersey: "Elastis Adem",
    materialCelana: "Spandek Balon",
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Lari", "Running", "Jogging"],
  },
  {
    id: "tokped-cpx-roadbike-set",
    name: "CPX Set Cycling Jersey Roadbike + Celana Padding Gel 3D",
    type: "set",
    price: 285000,
    discountPrice: 350000,
    image: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Premium",
    colors: ["Hitam", "Biru", "Merah"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "Setelan CPX Ultimate Comfort jersey sepeda gowes roadbike dengan celana spandex ketat pendek padding gel 3D. Comfort saddle untuk ride panjang.",
    materialJersey: "Dry Fit Milano",
    materialCelana: "Spandek Padding Gel 3D",
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Roadbike", "Gowes", "Sepeda"],
  },
  {
    id: "tokped-cpx-vintage-daily",
    name: "CPX Sport Jersey Vintage Dailywear Casual",
    type: "jersey",
    price: 99000,
    discountPrice: 130000,
    image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Vintage",
    colors: ["Biru Vinyl", "Hitam", "Cream"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "CPX Sport jersey vintage dailywear casual hangout nobar. Kaos olahraga retro yang cocok untuk nonton bareng dan aktivitas kasual.",
    materialJersey: "Cotton Combed 30s",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Casual", "Nobar", "Hangout"],
  },
  {
    id: "tokped-cpx-roadrunner",
    name: "CPX RoadRunner Jersey Lari Spandek Premium",
    type: "jersey",
    price: 125000,
    discountPrice: 155000,
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Running",
    colors: ["Biru", "Hitam", "Merah"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "CPX RoadRunner baju lari spandek premium jersey atasan olahraga pria. Dirancang untuk runner sejati dengan material stretch dan breathable.",
    materialJersey: "Spandek Premium",
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Lari", "Running", "Jogging"],
  },
  {
    id: "tokped-cpx-cycling-set-hut",
    name: "CPX Setelan Jersey HUT RI 79 + Celana Training",
    type: "set",
    price: 185000,
    discountPrice: 220000,
    image: "https://images.unsplash.com/photo-1524869924508-56f60b9bc4dc?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Limited Edition",
    colors: ["Merah Putih"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "CPX Sport setelan jersey baju sepeda pendek plus celana sepeda training panjang spesial HUT RI 79. Desain eksklusif warna merah putih.",
    materialJersey: "Dry Fit",
    materialCelana: "Training",
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Sepeda", "Training", "HUT RI"],
  },
  {
    id: "tokped-cpx-topi-seli",
    name: "Cycling Cap CPX Sport Topi Sepeda Seli MTB",
    type: "aksesoris",
    price: 55000,
    discountPrice: 75000,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c334e67a?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Aksesoris",
    colors: ["Hitam", "Biru", "Merah"],
    sizes: ["All Size"],
    description: "Cycling cap CPX Sport topi sepeda seli MTB downhill. Modern motif outdoor, melindungi dari matahari dan keringat.",
    materialJersey: null,
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Sepeda", "MTB", "Downhill"],
  },
  {
    id: "tokped-cpx-jaket-bomber",
    name: "CPX Jaket Bomber Pria Parka Musim Dingin",
    type: "outwear",
    price: 185000,
    discountPrice: 250000,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80",
    images: [],
    tag: "Outwear",
    colors: ["Hitam", "Navy", "Army"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "CPX jaket bomber pria jaket parka musim dingin. Classic jaket bulu Korea, hangat dan stylish. Cocok untuk cuaca dingin.",
    materialJersey: null,
    materialCelana: null,
    isCustom: false,
    minOrder: null,
    wholesalePrice: null,
    suitableFor: ["Outwear", "Casual", "Musim Dingin"],
  },
];

async function seedTokped() {
  const db = getDb();
  console.log("Seeding Tokopedia products...");

  await db.insert(products).values(
    tokpedProducts.map((p) => ({
      id: p.id,
      name: p.name,
      type: p.type,
      price: p.price,
      discountPrice: p.discountPrice ?? null,
      image: p.image,
      images: p.images,
      tag: p.tag ?? null,
      colors: p.colors,
      sizes: p.sizes,
      description: p.description,
      materialJersey: p.materialJersey ?? null,
      materialCelana: p.materialCelana ?? null,
      isCustom: p.isCustom ?? false,
      minOrder: p.minOrder ?? null,
      wholesalePrice: p.wholesalePrice ?? null,
      suitableFor: p.suitableFor ?? [],
    }))
  ).onConflictDoNothing();

  console.log(`  Inserted ${tokpedProducts.length} products from Tokopedia`);
  console.log("Done!");
  process.exit(0);
}

seedTokped().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
